MODEL:
  CLASSES: ("face", "face_mask",)
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("train",)
  TEST: ("val", )
  TYPE: "VOC" # VOC or COCO
  DATA_DIR: "./data/fm"
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-3

OUTPUT_DIR: "outputs/vgg_ssd300_voc0712"
